server:
  port: 9090
  servlet:
    context-path: /shop-manager

#Spring
spring:
  #数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    #指定druid连接池以及 druid连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1 #初始连接数
      max-active: 20  #最大连接数
      max-idle: 20    #最大空闲
      min-idle: 1     # 最小空闲
      max-wait: 60000 # 最长等待时间
  # freemarker模板引擎
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html;charset=UTF-8
    enabled: true
    suffix: .ftl
    template-loader-path: classpath:/views/
    request-context-attribute: request
    expose-request-attributes: true
    expose-spring-macro-helpers: true
    expose-session-attributes: true
    settings:
      tag_syntax: auto_detect
      template_update_delay: 0
      default_encoding: UTF-8              
      output_encoding: UTF-8
      locale: zh_CN                        
      date_format: yyyy-MM-dd              
      time_format: HH:mm:ss                
      datetime_format: yyyy-MM-dd HH:mm:ss
      number_format: #.##                  
      boolean_format: true,false
      template_exception_handler: html_debug
# MyBatis
mybatis:
#  #配置 MyBatis数据返回类型别名(默认别名是类名)
  type-aliases-package: com.xxxx.manager.pojo
  #配置 MyBatis Mapper 映射文件
  mapper-locations: classpath:/mapper/*.xml
## Mybatis SQL 打印(方法接口所在的包，不是 Mapper.xml 所在的包)
logging:
  level:
    com.xxxx.manager.mapper: debug